### ISSUE TITLE
sysbench 在超过很多链接数时会报错, 请添加如何更改 MySQL 的最大连接数的方法

### ISSUE THREAD

**Issue by abserari** [silverswords/mysql-insights#1]
现在默认是 151

```bash
MySQL [(none)]> show variables like '%max_connections%';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 151   |
+-----------------+-------+
1 row in set (0.005 sec)
```

**Comment by my-petrichor** [comment]
Thanks for reporting the issue.
using the follow SQL to modify mysql max_connections

    set global max_connections=200;

You can check again

    mysql> show variables like '%max_connections%';
    +-----------------+-------+
    | Variable_name   | Value |
    +-----------------+-------+
    | max_connections | 200   |
    +-----------------+-------+
